### ISSUE TITLE
Can not use the library with Angular 2.3.1

### ISSUE THREAD

**Issue by DavidGangel** [J-Siu/ng2-simple-timer#2]
I'm getting the following error in my console:
```
Unhandled Promise rejection: (SystemJS) Unexpected token < in JSON at position 2
	SyntaxError: Unexpected token < in JSON at position 2
	    at SystemJSLoader.instantiate (http://www.private.4cit-group.hu/skins/jspm_packages/github/systemjs/plugin-json@0.1.2/json.js:14:19)
	    at ZoneDelegate.invoke (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:229:26)
	    at Zone.run (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:113:43)
	    at http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:509:57
	    at ZoneDelegate.invokeTask (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:262:35)
	    at Zone.runTask (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:151:47)
	    at drainMicroTaskQueue (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:405:35)
	    at XMLHttpRequest.ZoneTask.invoke (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:336:25)
	Error loading http://www.private.4cit-group.hu/skins/jspm_packages/npm/elliptic@6.3.2/pac…ate.4cit-group.hu/skins/jspm_packages/github/systemjs/plugin-json@0.1.2.js as "../package.json!systemjs-json" from http://www.private.4cit-group.hu/skins/jspm_packages/npm/elliptic@6.3.2/lib/elliptic.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) Unexpected token < in JSON at position 2(…) (SystemJS) Unexpected token < in JSON at position 2
	SyntaxError: Unexpected token < in JSON at position 2
	    at SystemJSLoader.instantiate (http://www.private.4cit-group.hu/skins/jspm_packages/github/systemjs/plugin-json@0.1.2/json.js:14:19)
	    at ZoneDelegate.invoke (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:229:26)
	    at Zone.run (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:113:43)
	    at http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:509:57
	    at ZoneDelegate.invokeTask (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:262:35)
	    at Zone.runTask (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:151:47)
	    at drainMicroTaskQueue (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:405:35)
	    at XMLHttpRequest.ZoneTask.invoke (http://www.private.4cit-group.hu/skins/node_modules/zone.js/dist/zone.js:336:25)
	Error loading http://www.private.4cit-group.hu/skins/jspm_packages/npm/elliptic@6.3.2/pac…ate.4cit-group.hu/skins/jspm_packages/github/systemjs/plugin-json@0.1.2.js as "../package.json!systemjs-json" from http://www.private.4cit-group.hu/skins/jspm_packages/npm/elliptic@6.3.2/lib/elliptic.jsconsoleError @ zone.js:392_loop_1 @ zone.js:421drainMicroTaskQueue @ zone.js:425ZoneTask.invoke @ zone.js:336
zone.js:394 Error: Uncaught (in promise): Error: (SystemJS) Unexpected token < in JSON at position 2(…)consoleError @ zone.js:394_loop_1 @ zone.js:421drainMicroTaskQueue @ zone.js:425ZoneTask.invoke @ zone.js:336
```

I could imagine it's a side effect of my #1 bug as the RxJS version is different with the new angular.

**Comment by DavidGangel** [comment]
After a long googleing I found the solution to this issue.
Source:
http://blog.scottlogic.com/2015/12/24/creating-an-angular-2-build.html

system config.js should look like:
```
System.config({
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "angular2-google-maps/core": "jspm_packages/npm/angular2-google-maps/core/core.umd.js"
  },

  packages: {
    "angular2-google-maps/core": { defaultExtension: "js", main: "core.umd.js" },
    "app": { defaultExtension: "js", main: "./main.js" },
    "rxjs": { defaultExtension: "js" },
    'node-uuid': { format: "cjs", map: { crypto: "@empty" }
    }
  },

  map: {
    app: "app",
    immutable: "lib/immutable.js",
    "node-uuid": "lib/uuid.js",
.........
```

**Comment by J-Siu** [comment]
Updated to work with Angular 2.4.x. Please try.
